server:
  port: 9000
spring:
  application:
    name: SimpleProject
app:
  id: SimpleProject
apollo:
  meta: http://192.168.126.147:8080/
  bootstrap:
    enabled: true
    namespaces: application,common
